databases:
  - name: fuko_ziman_production
    databaseName: fuko_ziman_production
    user: fuko_ziman
    region: singapore

services:
  - type: web
    name: fuko_ziman_production
    env: ruby
    region: singapore
    plan: free
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: <%= ENV['DATABASE_URL'] %>
        fromDatabase:
          name: fuko_ziman_production
          property: connectionString
      - key: <%= ENV['RAILS_MASTER_KEY'] %>
        sync: false
